
export const ChurchConstants = {
  VIEW_CHURCHES_SUCCESS: 'VIEW_CHURCHES_SUCCESS',
  VIEW_CHURCHES_FAIL: 'VIEW_CHURCHES_FAIL',
  VIEW_POSTS_SUCCESS: 'VIEW_POSTS_SUCCESS',
  VIEW_POSTS_FAIL: 'VIEW_POSTS_FAIL',
};
